plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "CS374"
description: "Principles of Programming Languages"

url                      : https://BillJr99.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/Ursinus-CS374-Spring2021" # the subpath of your site, e.g. "/blog"
    
# Analytics  
google_analytics         : "UA-24052857-1"
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files

